### ISSUE TITLE
dirsInDirectory() or entriesInDirectory()

### ISSUE THREAD

**Issue by ComLock** [rbrastad/lib-filesystem#1]
filesInDirectory does not list directories so could I haz another function to do that?

I'm working on a file-explorer app in order to inspect what the third party OPS provider is doing...

https://github.com/ComLock/enonic-xp-admin-file-explorer

**Comment by ComLock** [comment]
https://bitbucket.org/openxp/lib-filesystem/pull-requests/1/dirsindirectory/diff

**Comment by rbrastad** [comment]
merged
